//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESBackupAndReplication.ESBackupServerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationResponse", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.App.Objects.Registration")]
    [System.SerializableAttribute()]
    public partial class RegistrationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ESBackupAndReplication.ESBackupServerService.ClientStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ESBackupAndReplication.ESBackupServerService.ClientStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientStatus", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects")]
    public enum ClientStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unverified = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Banned = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.App.Objects.Authentication" +
        "")]
    [System.SerializableAttribute()]
    public partial class LoginResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UTCExpirationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((this.SessionIDField.Equals(value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UTCExpiration {
            get {
                return this.UTCExpirationField;
            }
            set {
                if ((this.UTCExpirationField.Equals(value) != true)) {
                    this.UTCExpirationField = value;
                    this.RaisePropertyChanged("UTCExpiration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Configuration", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.App.Objects")]
    [System.SerializableAttribute()]
    public partial class Configuration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime GeneratedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReportIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusReportEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ESBackupAndReplication.ESBackupServerService.BackupTemplate[] TemplatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Generated {
            get {
                return this.GeneratedField;
            }
            set {
                if ((this.GeneratedField.Equals(value) != true)) {
                    this.GeneratedField = value;
                    this.RaisePropertyChanged("Generated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReportInterval {
            get {
                return this.ReportIntervalField;
            }
            set {
                if ((this.ReportIntervalField.Equals(value) != true)) {
                    this.ReportIntervalField = value;
                    this.RaisePropertyChanged("ReportInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StatusReportEnabled {
            get {
                return this.StatusReportEnabledField;
            }
            set {
                if ((this.StatusReportEnabledField.Equals(value) != true)) {
                    this.StatusReportEnabledField = value;
                    this.RaisePropertyChanged("StatusReportEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ESBackupAndReplication.ESBackupServerService.BackupTemplate[] Templates {
            get {
                return this.TemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplatesField, value) != true)) {
                    this.TemplatesField = value;
                    this.RaisePropertyChanged("Templates");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackupTemplate", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BackupTemplate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte BackupTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRONRepeatIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CompressionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<uint> DaysToExpirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEmailNotificationEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNotificationEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ESBackupAndReplication.ESBackupServerService.BackupTemplatePath[] PathsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchPatternField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte BackupType {
            get {
                return this.BackupTypeField;
            }
            set {
                if ((this.BackupTypeField.Equals(value) != true)) {
                    this.BackupTypeField = value;
                    this.RaisePropertyChanged("BackupType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRONRepeatInterval {
            get {
                return this.CRONRepeatIntervalField;
            }
            set {
                if ((object.ReferenceEquals(this.CRONRepeatIntervalField, value) != true)) {
                    this.CRONRepeatIntervalField = value;
                    this.RaisePropertyChanged("CRONRepeatInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Compression {
            get {
                return this.CompressionField;
            }
            set {
                if ((this.CompressionField.Equals(value) != true)) {
                    this.CompressionField = value;
                    this.RaisePropertyChanged("Compression");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<uint> DaysToExpiration {
            get {
                return this.DaysToExpirationField;
            }
            set {
                if ((this.DaysToExpirationField.Equals(value) != true)) {
                    this.DaysToExpirationField = value;
                    this.RaisePropertyChanged("DaysToExpiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDClient {
            get {
                return this.IDClientField;
            }
            set {
                if ((this.IDClientField.Equals(value) != true)) {
                    this.IDClientField = value;
                    this.RaisePropertyChanged("IDClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEmailNotificationEnabled {
            get {
                return this.IsEmailNotificationEnabledField;
            }
            set {
                if ((this.IsEmailNotificationEnabledField.Equals(value) != true)) {
                    this.IsEmailNotificationEnabledField = value;
                    this.RaisePropertyChanged("IsEmailNotificationEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNotificationEnabled {
            get {
                return this.IsNotificationEnabledField;
            }
            set {
                if ((this.IsNotificationEnabledField.Equals(value) != true)) {
                    this.IsNotificationEnabledField = value;
                    this.RaisePropertyChanged("IsNotificationEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ESBackupAndReplication.ESBackupServerService.BackupTemplatePath[] Paths {
            get {
                return this.PathsField;
            }
            set {
                if ((object.ReferenceEquals(this.PathsField, value) != true)) {
                    this.PathsField = value;
                    this.RaisePropertyChanged("Paths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchPattern {
            get {
                return this.SearchPatternField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchPatternField, value) != true)) {
                    this.SearchPatternField = value;
                    this.RaisePropertyChanged("SearchPattern");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackupTemplatePath", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BackupTemplatePath : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDBackupTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PathOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TargetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDBackupTemplate {
            get {
                return this.IDBackupTemplateField;
            }
            set {
                if ((this.IDBackupTemplateField.Equals(value) != true)) {
                    this.IDBackupTemplateField = value;
                    this.RaisePropertyChanged("IDBackupTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PathOrder {
            get {
                return this.PathOrderField;
            }
            set {
                if ((this.PathOrderField.Equals(value) != true)) {
                    this.PathOrderField = value;
                    this.RaisePropertyChanged("PathOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TargetType {
            get {
                return this.TargetTypeField;
            }
            set {
                if ((this.TargetTypeField.Equals(value) != true)) {
                    this.TargetTypeField = value;
                    this.RaisePropertyChanged("TargetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BackupInfo", Namespace="http://schemas.datacontract.org/2004/07/ESBackupServer.Database.Objects", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BackupInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte BackupTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BaseBackupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CompressedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDBackupTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PathOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UTCEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UTCExpirationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UTCStartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte BackupType {
            get {
                return this.BackupTypeField;
            }
            set {
                if ((this.BackupTypeField.Equals(value) != true)) {
                    this.BackupTypeField = value;
                    this.RaisePropertyChanged("BackupType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BaseBackupID {
            get {
                return this.BaseBackupIDField;
            }
            set {
                if ((this.BaseBackupIDField.Equals(value) != true)) {
                    this.BaseBackupIDField = value;
                    this.RaisePropertyChanged("BaseBackupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Compressed {
            get {
                return this.CompressedField;
            }
            set {
                if ((this.CompressedField.Equals(value) != true)) {
                    this.CompressedField = value;
                    this.RaisePropertyChanged("Compressed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailSent {
            get {
                return this.EmailSentField;
            }
            set {
                if ((this.EmailSentField.Equals(value) != true)) {
                    this.EmailSentField = value;
                    this.RaisePropertyChanged("EmailSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDBackupTemplate {
            get {
                return this.IDBackupTemplateField;
            }
            set {
                if ((this.IDBackupTemplateField.Equals(value) != true)) {
                    this.IDBackupTemplateField = value;
                    this.RaisePropertyChanged("IDBackupTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDClient {
            get {
                return this.IDClientField;
            }
            set {
                if ((this.IDClientField.Equals(value) != true)) {
                    this.IDClientField = value;
                    this.RaisePropertyChanged("IDClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PathOrder {
            get {
                return this.PathOrderField;
            }
            set {
                if ((this.PathOrderField.Equals(value) != true)) {
                    this.PathOrderField = value;
                    this.RaisePropertyChanged("PathOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UTCEnd {
            get {
                return this.UTCEndField;
            }
            set {
                if ((this.UTCEndField.Equals(value) != true)) {
                    this.UTCEndField = value;
                    this.RaisePropertyChanged("UTCEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UTCExpiration {
            get {
                return this.UTCExpirationField;
            }
            set {
                if ((this.UTCExpirationField.Equals(value) != true)) {
                    this.UTCExpirationField = value;
                    this.RaisePropertyChanged("UTCExpiration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UTCStart {
            get {
                return this.UTCStartField;
            }
            set {
                if ((this.UTCStartField.Equals(value) != true)) {
                    this.UTCStartField = value;
                    this.RaisePropertyChanged("UTCStart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ESBackupServerService.IESBackupServerService")]
    public interface IESBackupServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/RequestRegistration", ReplyAction="http://tempuri.org/IESBackupServerService/RequestRegistrationResponse")]
        ESBackupAndReplication.ESBackupServerService.RegistrationResponse RequestRegistration(string name, string hwid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/RequestRegistration", ReplyAction="http://tempuri.org/IESBackupServerService/RequestRegistrationResponse")]
        System.Threading.Tasks.Task<ESBackupAndReplication.ESBackupServerService.RegistrationResponse> RequestRegistrationAsync(string name, string hwid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/Login", ReplyAction="http://tempuri.org/IESBackupServerService/LoginResponse")]
        ESBackupAndReplication.ESBackupServerService.LoginResponse Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/Login", ReplyAction="http://tempuri.org/IESBackupServerService/LoginResponse")]
        System.Threading.Tasks.Task<ESBackupAndReplication.ESBackupServerService.LoginResponse> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/Logout", ReplyAction="http://tempuri.org/IESBackupServerService/LogoutResponse")]
        bool Logout(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/Logout", ReplyAction="http://tempuri.org/IESBackupServerService/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/GetConfiguration", ReplyAction="http://tempuri.org/IESBackupServerService/GetConfigurationResponse")]
        ESBackupAndReplication.ESBackupServerService.Configuration GetConfiguration(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/GetConfiguration", ReplyAction="http://tempuri.org/IESBackupServerService/GetConfigurationResponse")]
        System.Threading.Tasks.Task<ESBackupAndReplication.ESBackupServerService.Configuration> GetConfigurationAsync(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/CreateBackup", ReplyAction="http://tempuri.org/IESBackupServerService/CreateBackupResponse")]
        void CreateBackup(ESBackupAndReplication.ESBackupServerService.BackupInfo backup, System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/CreateBackup", ReplyAction="http://tempuri.org/IESBackupServerService/CreateBackupResponse")]
        System.Threading.Tasks.Task CreateBackupAsync(ESBackupAndReplication.ESBackupServerService.BackupInfo backup, System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/HasConfigUpdate", ReplyAction="http://tempuri.org/IESBackupServerService/HasConfigUpdateResponse")]
        bool HasConfigUpdate(System.Guid sessionID, System.DateTime timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/HasConfigUpdate", ReplyAction="http://tempuri.org/IESBackupServerService/HasConfigUpdateResponse")]
        System.Threading.Tasks.Task<bool> HasConfigUpdateAsync(System.Guid sessionID, System.DateTime timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/ClientReportUpdated", ReplyAction="http://tempuri.org/IESBackupServerService/ClientReportUpdatedResponse")]
        void ClientReportUpdated(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IESBackupServerService/ClientReportUpdated", ReplyAction="http://tempuri.org/IESBackupServerService/ClientReportUpdatedResponse")]
        System.Threading.Tasks.Task ClientReportUpdatedAsync(System.Guid sessionID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IESBackupServerServiceChannel : ESBackupAndReplication.ESBackupServerService.IESBackupServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ESBackupServerServiceClient : System.ServiceModel.ClientBase<ESBackupAndReplication.ESBackupServerService.IESBackupServerService>, ESBackupAndReplication.ESBackupServerService.IESBackupServerService {
        
        public ESBackupServerServiceClient() {
        }
        
        public ESBackupServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ESBackupServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBackupServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ESBackupServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ESBackupAndReplication.ESBackupServerService.RegistrationResponse RequestRegistration(string name, string hwid) {
            return base.Channel.RequestRegistration(name, hwid);
        }
        
        public System.Threading.Tasks.Task<ESBackupAndReplication.ESBackupServerService.RegistrationResponse> RequestRegistrationAsync(string name, string hwid) {
            return base.Channel.RequestRegistrationAsync(name, hwid);
        }
        
        public ESBackupAndReplication.ESBackupServerService.LoginResponse Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<ESBackupAndReplication.ESBackupServerService.LoginResponse> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool Logout(System.Guid sessionID) {
            return base.Channel.Logout(sessionID);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(System.Guid sessionID) {
            return base.Channel.LogoutAsync(sessionID);
        }
        
        public ESBackupAndReplication.ESBackupServerService.Configuration GetConfiguration(System.Guid sessionID) {
            return base.Channel.GetConfiguration(sessionID);
        }
        
        public System.Threading.Tasks.Task<ESBackupAndReplication.ESBackupServerService.Configuration> GetConfigurationAsync(System.Guid sessionID) {
            return base.Channel.GetConfigurationAsync(sessionID);
        }
        
        public void CreateBackup(ESBackupAndReplication.ESBackupServerService.BackupInfo backup, System.Guid sessionID) {
            base.Channel.CreateBackup(backup, sessionID);
        }
        
        public System.Threading.Tasks.Task CreateBackupAsync(ESBackupAndReplication.ESBackupServerService.BackupInfo backup, System.Guid sessionID) {
            return base.Channel.CreateBackupAsync(backup, sessionID);
        }
        
        public bool HasConfigUpdate(System.Guid sessionID, System.DateTime timestamp) {
            return base.Channel.HasConfigUpdate(sessionID, timestamp);
        }
        
        public System.Threading.Tasks.Task<bool> HasConfigUpdateAsync(System.Guid sessionID, System.DateTime timestamp) {
            return base.Channel.HasConfigUpdateAsync(sessionID, timestamp);
        }
        
        public void ClientReportUpdated(System.Guid sessionID) {
            base.Channel.ClientReportUpdated(sessionID);
        }
        
        public System.Threading.Tasks.Task ClientReportUpdatedAsync(System.Guid sessionID) {
            return base.Channel.ClientReportUpdatedAsync(sessionID);
        }
    }
}
